name: canto_crave
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  velocity_x: 4.1.0
  flutter:
    sdk: flutter
  collection: ^1.17.1 
  provider:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  card_swiper: ^3.0.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_layout_grid: ^2.0.4
  firebase_database: ^10.2.4
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.5
  intl: ^0.18.1
  google_sign_in: ^6.1.4
  upi_payment_qrcode_generator: ^1.4.0
  test_api: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: elMessiri
      fonts:
        - asset: fonts/font.ttf
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/food_items/burger.png
    - images/food_items/Maggie-Omelette.jpeg
    - images/food_items/noodles.png
    - images/food_items/beverages.png
    - images/food_items/chinese.png
    - images/food_items/rolls.png
    - images/1.png
    - images/3.png
    - images/2.png
    - images/google_logo.png

flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true